spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
server:
  port: 8080
logging:
  level:
    root: INFO
    com:
      nayonikaeyecare: INFO
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600

auth:
  excluded:
    path: /auth,/v3/api-docs,/swagger-ui,/swagger-resources

fast2sms:
  apikey: ${FAST2SMS_API_KEY}
pii:
  encryption:
    key: ${PII_ENCRYPTION_KEY:B8gmQSVarw9sWLx2Mh5gS5Cj2Qp7nC5zTjLg8fVbZ7U=} # FOR DEVELOPMENT ONLY - REPLACE WITH SECURE KEY FROM ENV VAR
