spring:
  application:
    name: api
  data:
    mongodb:
      uri: mongodb+srv://nayonikamanager:tsJq4RcfhTFIGHQB@nayonikaDev.1quayyj.mongodb.net/
      database: nayonikaDev
server:
  port: 8081

jwt:
  secret: "thisisasecretkeythatis32byteslongButNotReallyAndItShouldBeKeptSecret"
  expiration: 3600
auth:
  excluded:
    path: /auth,/v3/api-docs,/swagger-ui,/swagger-resources
fast2sms:
  apikey: "ss"
pii:
  encryption:
    key: "B8gmQSVarw9sWLx2Mh5gS5Cj2Qp7nC5zTjLg8fVbZ7U=" # FOR DEVELOPMENT ONLY - REPLACE WITH SECURE KEY FROM ENV VAR

