spring:
  data:
    mongodb:
      uri: mongodb+srv://nayonikaeyecare:b7yjInwQUxCCghBT@nayonikacluster.fqrcfog.mongodb.net/nayonikaDev
      database: nayonikaDev
server:
  port: 8084

jwt:
  secret: "thisisasecretkeythatis32byteslongButNotReallyAndItShouldBeKeptSecret"
  expiration: 3600

auth:
  excluded:
    path: /auth,/v3/api-docs,/swagger-ui,/swagger-resources
