spring:
  application:
    name: api
  data:
    mongodb:
      uri: mongodb+srv://nayonikaeyecare:b7yjInwQUxCCghBT@nayonikacluster.fqrcfog.mongodb.net/nayonikaDev
      database: nayonikaDev
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
server:
  port: 8081
 
jwt:
  secret: "thisisasecretkeythatis32byteslongButNotReallyAndItShouldBeKeptSecret"
  expiration: 3600
auth:
  excluded:
    path: /auth,/v3/api-docs,/swagger-ui,/swagger-resources
    
logging:
  level:
    "[org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer]": error
 
pii:
  encryption:
    key: ${PII_ENCRYPTION_KEY}

app:
  security:
    hmac-secret-key: "your-super-secret-hmac-key-change-me-in-prod" # IMPORTANT: Change this in production and use env variables or Vault